version: "3"

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.60.1.0/16

services:

  php:
    container_name: php
    build:
      context: docker/php
    environment:
      DB_CONNECTION: mysql
      DB_HOST: 172.60.1.2
      DB_PORT: 3306
      DB_DATABASE: pastry_shop
      DB_USERNAME: root
      DB_PASSWORD: secret
    volumes:
      - .:/opt/pastry_shop
    networks:
      default:
         ipv4_address: 172.60.1.1

  mysql:
    container_name: mysql
    image: mysql:5.7.28
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: pastry_shop
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3307:3306
    networks:
      default:
         ipv4_address: 172.60.1.2

  web:
    container_name: web
    image: nginx:latest
    volumes:
      - ./:/opt/pastry_shop
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/site.conf
    depends_on:
      - php
    ports:
      - 8080:8080
    networks:
      default:
         ipv4_address: 172.60.1.3

